"""engine.py — workbook classification and engine routing.

Phase 1a — IMPLEMENTED.

classify_workbook(path) is the spine of the entire server: every write op calls it
to decide which engine is safe to use for that file.

Engine routing table
--------------------
| Target state                               | Engine          | Rule     |
|--------------------------------------------|-----------------|----------|
| New / nonexistent                          | OPENPYXL        | —        |
| Exists, no populated <v> under <f>         | OPENPYXL        | safe     |
| Exists, has cached formula values          | LIBREOFFICE     | Rule 0   |
| Exists, has _xlfn/XLOOKUP/LAMBDA/IFS/array | XML_SURGERY     | Rule 0b  |
| File is open in Excel (any state)          | EXCEL_LIVE      | Phase 2  |

Rule 0  — never openpyxl-load-modify-save a computed workbook.
Rule 0b — never LibreOffice-recalc a dynamic-array/LAMBDA workbook
          (cascades to #N/A; XML surgery or Excel AppleScript required).
"""
from __future__ import annotations

import hashlib
import re
import zipfile
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Engine(str, Enum):
    """Safe write-engine choices for a given workbook state."""
    OPENPYXL    = "openpyxl"      # New or no cached values — safe to load/modify/save
    LIBREOFFICE = "libreoffice"   # Computed workbook — must use headless macro recalc
    XML_SURGERY = "xml_surgery"   # Dynamic-array/LAMBDA — openpyxl and LO both unsafe
    EXCEL_LIVE  = "excel_live"    # File open in Excel — AppleScript bridge only (Phase 2)


# ---------------------------------------------------------------------------
# Detection helpers (pure functions, no I/O except accepting a ZipFile)
# ---------------------------------------------------------------------------

# Regex: cells with BOTH a formula (<f>) AND a non-empty cached value (<v>).
# Matches the sequence </f> ... <v>non-empty</v> within the same cell.
# Literal-value cells have <v> but NO <f> — they must not trigger LIBREOFFICE routing,
# because openpyxl can safely overwrite them (they have no cached formula values to lose).
# Note: in xlsx XML, <f> always precedes <v> within a cell element, so matching
# </f>[whitespace]<v>content</v> is reliable across both Excel and LO output.
_RE_CACHED_FORMULA_V = re.compile(r"</f>\s*<v>[^<\s][^<]*</v>")

# Dynamic-array / LAMBDA markers in formula text
_DYNAMIC_ARRAY_STRINGS = (
    "_xlfn.",
    "XLOOKUP",
    "LAMBDA",
    "FILTER(",
    "SORT(",
    "SORTBY(",
    "UNIQUE(",
    "SEQUENCE(",
    "RANDARRAY(",
    "XMATCH(",
    'IFS(',
    "LET(",
    't="array"',
    "t='array'",
    "<f t=",
    'cm="',
    'vm="',
)


def _scan_sheet_xml(xml: str) -> tuple[bool, bool]:
    """Scan one worksheet XML for cached values and dynamic-array markers.

    has_cached_values is True only when a FORMULA cell (<f>…</f>) has a
    non-empty cached value (<v>…</v>). Literal-value cells (no <f>) are ignored
    so that a freshly-built openpyxl workbook with only input values correctly
    routes to OPENPYXL, not LIBREOFFICE.

    Returns:
        (has_cached_values, has_dynamic_arrays)
    """
    has_cached = bool(_RE_CACHED_FORMULA_V.search(xml))
    has_dynamic = any(marker in xml for marker in _DYNAMIC_ARRAY_STRINGS)
    return has_cached, has_dynamic


def _has_metadata_xml(zf: zipfile.ZipFile) -> bool:
    """Check for xl/metadata.xml which is generated by dynamic-array formulas."""
    return "xl/metadata.xml" in zf.namelist()


def _extract_sheet_names(zf: zipfile.ZipFile) -> list[str]:
    """Return worksheet display names from xl/workbook.xml (order-preserved)."""
    try:
        xml = zf.read("xl/workbook.xml").decode("utf-8", errors="replace")
        # <sheet name="Sheet1" sheetId="1" r:id="rId1"/>
        return re.findall(r'<sheet\b[^>]*\bname="([^"]+)"', xml)
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

@dataclass
class WorkbookClass:
    """Result of classify_workbook()."""
    engine: Engine
    has_cached_values: bool
    has_dynamic_arrays: bool
    is_open_in_excel: bool
    sheets: list[str]
    disk_hash: str | None          # None when path does not exist
    path: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "engine": self.engine.value,
            "has_cached_values": self.has_cached_values,
            "has_dynamic_arrays": self.has_dynamic_arrays,
            "is_open_in_excel": self.is_open_in_excel,
            "sheets": self.sheets,
            "disk_hash": self.disk_hash,
            "path": self.path,
        }


def classify_workbook(path: str | Path) -> WorkbookClass:
    """Inspect *path* and return engine recommendation plus workbook metadata.

    Scans the xlsx ZIP without loading with openpyxl (avoids triggering Rule 0
    side-effects). Falls back gracefully if a sheet is malformed.

    Args:
        path: Absolute path to the .xlsx / .xlsm file (need not exist yet).

    Returns:
        WorkbookClass with engine, has_cached_values, has_dynamic_arrays, etc.
    """
    p = Path(path)

    # ── New / nonexistent ──────────────────────────────────────────────────
    if not p.exists():
        return WorkbookClass(
            engine=Engine.OPENPYXL,
            has_cached_values=False,
            has_dynamic_arrays=False,
            is_open_in_excel=False,
            sheets=[],
            disk_hash=None,
            path=str(p),
        )

    # ── Open-in-Excel check (lock-file heuristic for Phase 1; full probe in Phase 2) ──
    open_in_excel = _check_lock_file(p)

    # ── Scan ZIP contents ─────────────────────────────────────────────────
    has_cached = False
    has_dynamic = False
    sheets: list[str] = []

    try:
        with zipfile.ZipFile(p, "r") as zf:
            sheets = _extract_sheet_names(zf)

            # Check xl/metadata.xml for dynamic-array provenance
            if _has_metadata_xml(zf):
                has_dynamic = True

            # Scan each worksheet XML
            for name in zf.namelist():
                if not (name.startswith("xl/worksheets/sheet") and name.endswith(".xml")):
                    continue
                try:
                    xml = zf.read(name).decode("utf-8", errors="replace")
                    c, d = _scan_sheet_xml(xml)
                    if c:
                        has_cached = True
                    if d:
                        has_dynamic = True
                except Exception:
                    # Tolerate malformed sheets; fail safe toward LIBREOFFICE
                    has_cached = True

    except zipfile.BadZipFile:
        # Not a valid xlsx — let caller decide; return OPENPYXL so it errors on use
        return WorkbookClass(
            engine=Engine.OPENPYXL,
            has_cached_values=False,
            has_dynamic_arrays=False,
            is_open_in_excel=open_in_excel,
            sheets=[],
            disk_hash=disk_hash(p),
            path=str(p),
        )

    # ── Choose engine ──────────────────────────────────────────────────────
    if open_in_excel:
        engine = Engine.EXCEL_LIVE
    elif has_dynamic:
        engine = Engine.XML_SURGERY  # Rule 0b: refuse automated edit; Phase 3 handles this
    elif has_cached:
        engine = Engine.LIBREOFFICE  # Rule 0: must preserve cached values
    else:
        engine = Engine.OPENPYXL     # Safe: no cached values to lose

    return WorkbookClass(
        engine=engine,
        has_cached_values=has_cached,
        has_dynamic_arrays=has_dynamic,
        is_open_in_excel=open_in_excel,
        sheets=sheets,
        disk_hash=disk_hash(p),
        path=str(p),
    )


def disk_hash(path: str | Path) -> str:
    """Return a SHA-256 hex digest of the file at *path*.

    Used by the staleness guard: every file-engine read caches this hash;
    a write refuses if the on-disk hash has changed since the last read.

    Raises:
        FileNotFoundError: If path does not exist.
    """
    p = Path(path)
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def is_open_in_excel(path: str | Path) -> bool:
    """Return True if *path* is currently open in Microsoft Excel.

    Phase 1 implementation: lock-file heuristic only.
    Phase 2 will add a full AppleScript probe.

    The lock file ~$<name>.xlsx is created by Excel (and Word) when a file is open.
    Fail-safe: returns True when in doubt (prevents file-engine clobber).

    Args:
        path: Absolute path to the workbook.
    """
    return _check_lock_file(Path(path))


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _check_lock_file(p: Path) -> bool:
    """Check for the Excel lock file ~$<stem><suffix> in the same directory."""
    lock = p.parent / f"~${p.name}"
    return lock.exists()
